/*
    Hello World Program
    > hello_world

    rustc main.rs
    ./main
*/

// main() function
fn main() {
    println!("Welcome to Rust!");
}

/*
    The rustup command can be used to update, uninstall, or view the Rust Docs.

    The cargo command allows manage Rust projects from the CLI.
    - Rust projects are also known as crates or packages.
        > a binary crate is a standalone Rust application that runs in isolation
        > a library crate is one that will be used within other Rust projects

    The src directory is where the source code of the application will live.

    The target directory is where the compiler will place the executable program.

    The Cargo.toml file is a text file of key-value pairs which outline the definitions/meta-data of the Rust project.

    The Cargo.lock is automatically generated by cargo, and keeps track of dependencies/crates & versions.

    The cargo build command will compile the entire Rust cargo project (from the top-level).
    - the cargo build command will build the project in debug mode (by default)
    - all Rust src code -> 1 executable

    The cargo clean command will "clean up" the project by deleting any target executables (debug or release).

    The cargo run command will build and run the target executable.

    The cargo check command checks the source code for any compiler violations, but does not produce an executable.
    - any error that causes the compiler to be unable to build the source code.
*/