/*
    Hello World Program
    > hello_world
*/

fn main() {
    println!("Welcome to Rust!");
}

/*
    The rustup command can be used to update, uninstall, or view the Rust Docs.

    The cargo command allows manage Rust projects from the CLI.
    - Rust projects are also known as crates or packages.
        > a binary crate is a standalone Rust application that runs in isolation.
        > a library crate is one that will be used within other Rust projects.

    The src directory is where the source code of the application will live.

    The target directory is where the compiler will place the executable program.

    The Cargo.toml file is a text file of key-value pairs which outline the definitions/meta-data of the Rust project.

    The Cargo.lock is automatically generated by cargo, and keeps track of dependencies/crates & versions.
*/